[project]
name = "qwen-code-proxy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "litellm[proxy]>=1.80.10",
    "python-dotenv>=1.0.0",
    "uvicorn>=0.31.1",
]
